const standards = {
    text1:{
        top: 0,
        left: 0,
        size: 60,
        color: '#000',
        width: 200,
        height: 100,
        font_weight: 'bold',
        value:'大标题',
        lable:'大标题',
        type:'text'
    },
    text2:{
        top: 0,
        left: 0,
        size: 40,
        color: '#000',
        width: 150,
        height:70,
        font_weight: 'bold',
        value:'标题',
        lable:'标题',
        type:'text'
    },
    text3:{
        top: 0,
        left: 0,
        size: 30,
        color: '#000',
        width: 120,
        height: 50,
        font_weight: '500',
        value:'副标题',
        lable:'副标题',
        type:'text'
    },
    text4:{
        top: 0,
        left: 0,
        size: 16,
        color: '#000',
        width: 100,
        height: 30,
        font_weight: '500',
        value:'正文内容',
        lable:'正文内容',
        type:'text'
    },
    shape1:{
        top: 0,
        left: 0,
        background_color: '#000',
        width: 100,
        height:100,
        border_width: 0,
        border_style:'solid',
        border_color: null,
        font_weight: '',
        value:'',
        radius: 0,
        lable:'实心矩形',
        type:'rect'
    },
    shape2:{
        top: 0,
        left: 0,
        background_color: '#000',
        width: 100,
        height:100,
        border_width: 0,
        border_style:'solid',
        border_color: null,
        radius: 50,
        font_weight: '',
        value:'',
        lable:'实心圆形',
        type:'rect'
    },
    shape3:{
        top: 0,
        left: 0,
        background_color: null,
        border_width:5,
        border_style:'solid',
        border_color:'#000',
        width: 100,
        height:100,
        font_weight: '',
        value:'',
        radius: 0,
        lable:'空心矩形',
        type:'rect'
    },
    shape4:{
        top: 0,
        left: 0,
        background_color: null,
        border_width:5,
        border_style:'solid',
        border_color:'#000',
        width: 100,
        height:100,
        radius: 50,
        font_weight: '',
        value:'',
        lable:'空心圆形',
        type:'rect'
    }
}
export default standards